CREATE DATABASE IF NOT EXISTS genius;
USE genius;
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) UNIQUE, password VARCHAR(255), is_active BOOLEAN DEFAULT TRUE, tier VARCHAR(50) DEFAULT 'free', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
